<?php

namespace App\Services\Fixpulse;

use App\Models\Issue;
use App\Models\IssueAction;
use App\Models\User;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use RuntimeException;

class IssueActionService
{
    public function __construct(
        private readonly BranchNamingService $branchNaming,
        private readonly GitRepositoryService $git,
        private readonly GithubPrService $githubPr,
        private readonly AutoFixService $autoFix,
    ) {
    }

    public function generatePatch(Issue $issue, User $user): IssueAction
    {
        $branch = $this->branchNaming->branchForIssue($issue);
        $commitMessage = $this->branchNaming->commitMessage($issue);

        $patch = [
            'issue_key' => $issue->key,
            'issue_title' => $issue->title,
            'severity' => $issue->severity,
            'target_paths' => $this->suggestTargetPaths((string) $issue->key),
            'steps_en' => data_get($issue->fix_jsonb, 'steps', []),
            'summary_es' => data_get($issue->fix_jsonb, 'summary'),
            'resources' => $issue->resources->take(12)->map(fn ($r) => [
                'url' => $r->url,
                'type' => $r->resource_type,
                'transfer_size_kb' => $r->transfer_size_kb,
                'wasted_kb' => data_get($r->details_jsonb, 'wasted_kb'),
                'selector' => data_get($r->details_jsonb, 'selector'),
            ])->values()->all(),
            'guards' => [
                'allowed_globs' => config('fixpulse_actions.guards.allowed_globs'),
                'blocked_globs' => config('fixpulse_actions.guards.blocked_globs'),
            ],
            'confidence' => $this->confidenceForIssue((string) $issue->key),
        ];

        return IssueAction::query()->create([
            'issue_id' => $issue->id,
            'user_id' => $user->id,
            'kind' => 'generate_patch',
            'status' => 'ready',
            'branch_name' => $branch,
            'commit_message' => $commitMessage,
            'patch_jsonb' => $patch,
            'meta_jsonb' => [
                'generated_at' => now()->toIso8601String(),
            ],
        ]);
    }

    public function createPr(Issue $issue, User $user): IssueAction
    {
        return DB::transaction(function () use ($issue, $user): IssueAction {
            $proposal = $issue->actions()
                ->where('kind', 'generate_patch')
                ->latest('id')
                ->first();

            if (! $proposal) {
                $proposal = $this->generatePatch($issue, $user);
            }

            $repoPath = $this->git->repoPath();
            $this->git->assertRepository($repoPath);

            $branch = (string) ($proposal->branch_name ?: $this->branchNaming->branchForIssue($issue));
            $commitMessage = (string) ($proposal->commit_message ?: $this->branchNaming->commitMessage($issue));
            $defaultBranch = $this->git->defaultBranch();

            $this->git->checkoutDefaultBranch($repoPath);
            $this->git->createOrResetBranch($repoPath, $branch);

            $relativeFile = sprintf(
                'resources/fixpulse_actions/scan-%d/%s.md',
                (int) $issue->scan_id,
                $this->branchNaming->issueKeyToSlug((string) $issue->key)
            );
            $this->git->guardPathAllowed($relativeFile);

            $absFile = $repoPath.DIRECTORY_SEPARATOR.str_replace('/', DIRECTORY_SEPARATOR, $relativeFile);
            File::ensureDirectoryExists(dirname($absFile));

            $markdown = $this->buildProposalMarkdown($issue, (array) $proposal->patch_jsonb);
            File::put($absFile, $markdown);

            $autofix = $this->autoFix->apply($issue, $repoPath);
            $changedFiles = array_values(array_unique(array_merge([$relativeFile], (array) ($autofix['changed_files'] ?? []))));
            foreach ($changedFiles as $path) {
                $this->git->add($repoPath, $path);
            }

            $diffText = $this->git->diffForPaths($repoPath, $changedFiles);
            $sha = $this->git->commit($repoPath, $commitMessage);
            $this->git->pushBranch($repoPath, $branch);

            $repo = (string) config('services.github.repo', '');
            if ($repo === '') {
                $repo = (string) ($this->git->originRepoFullName($repoPath) ?? '');
            }
            if ($repo === '') {
                throw new RuntimeException('Unable to determine GitHub repo full name (owner/repo). Set GITHUB_REPO.');
            }

            $prTitle = $commitMessage;
            $prBody = "Generated by FixPulse.\n\n- Scan: #{$issue->scan_id}\n- Issue: {$issue->key}\n- Severity: {$issue->severity}\n";

            $pr = $this->githubPr->createPullRequest($repo, $prTitle, $prBody, $branch, $defaultBranch);

            return IssueAction::query()->create([
                'issue_id' => $issue->id,
                'user_id' => $user->id,
                'kind' => 'create_pr',
                'status' => 'completed',
                'branch_name' => $branch,
                'commit_message' => $commitMessage,
                'commit_sha' => $sha,
                'pr_url' => $pr['url'] ?: null,
                'pr_number' => $pr['number'],
                'patch_jsonb' => $proposal->patch_jsonb,
                'diff_text' => $diffText,
                'meta_jsonb' => [
                    'proposal_action_id' => $proposal->id,
                    'proposal_file' => $relativeFile,
                    'repo' => $repo,
                    'autofix' => $autofix,
                ],
            ]);
        });
    }

    public function revertPr(Issue $issue, User $user): IssueAction
    {
        return DB::transaction(function () use ($issue, $user): IssueAction {
            $lastPrAction = $issue->actions()
                ->where('kind', 'create_pr')
                ->where('status', 'completed')
                ->latest('id')
                ->first();

            if (! $lastPrAction || ! $lastPrAction->commit_sha) {
                throw new RuntimeException('No completed PR action with commit SHA found for this issue.');
            }

            $repoPath = $this->git->repoPath();
            $this->git->assertRepository($repoPath);
            $defaultBranch = $this->git->defaultBranch();

            $suffix = now()->format('YmdHis');
            $branch = sprintf(
                'fixpulse/revert-%d-%s-%s',
                (int) $issue->scan_id,
                $this->branchNaming->issueKeyToSlug((string) $issue->key),
                $suffix
            );
            $commitMessage = sprintf(
                'revert(scan:%d): %s',
                (int) $issue->scan_id,
                $this->branchNaming->issueKeyToSlug((string) $issue->key)
            );

            $this->git->checkoutDefaultBranch($repoPath);
            $this->git->createOrResetBranch($repoPath, $branch);
            $sha = $this->git->revertCommit($repoPath, (string) $lastPrAction->commit_sha);
            $this->git->pushBranch($repoPath, $branch);

            $repo = (string) config('services.github.repo', '');
            if ($repo === '') {
                $repo = (string) ($this->git->originRepoFullName($repoPath) ?? '');
            }
            if ($repo === '') {
                throw new RuntimeException('Unable to determine GitHub repo full name (owner/repo). Set GITHUB_REPO.');
            }

            $pr = $this->githubPr->createPullRequest(
                $repo,
                $commitMessage,
                "Revert PR generated by FixPulse.\n\n- Original action: #{$lastPrAction->id}\n- Original commit: {$lastPrAction->commit_sha}",
                $branch,
                $defaultBranch
            );

            return IssueAction::query()->create([
                'issue_id' => $issue->id,
                'user_id' => $user->id,
                'kind' => 'revert_pr',
                'status' => 'completed',
                'branch_name' => $branch,
                'commit_message' => $commitMessage,
                'commit_sha' => $sha,
                'pr_url' => $pr['url'] ?: null,
                'pr_number' => $pr['number'],
                'meta_jsonb' => [
                    'reverted_action_id' => $lastPrAction->id,
                    'reverted_commit_sha' => $lastPrAction->commit_sha,
                    'repo' => $repo,
                ],
            ]);
        });
    }

    private function buildProposalMarkdown(Issue $issue, array $proposal): string
    {
        $lines = [];
        $lines[] = '# FixPulse Patch Proposal';
        $lines[] = '';
        $lines[] = '- Scan ID: `'.$issue->scan_id.'`';
        $lines[] = '- Issue Key: `'.$issue->key.'`';
        $lines[] = '- Severity: `'.$issue->severity.'`';
        $lines[] = '- Impact: `'.$issue->impact_score.'`';
        $lines[] = '- Effort: `'.$issue->effort_score.'`';
        $lines[] = '';
        $lines[] = '## Summary (ES)';
        $lines[] = '';
        $lines[] = (string) ($proposal['summary_es'] ?? 'N/A');
        $lines[] = '';
        $lines[] = '## Suggested Paths';
        $lines[] = '';

        foreach ((array) Arr::get($proposal, 'target_paths', []) as $path) {
            $lines[] = '- `'.$path.'`';
        }

        $lines[] = '';
        $lines[] = '## Steps (EN)';
        $lines[] = '';
        foreach ((array) Arr::get($proposal, 'steps_en', []) as $step) {
            $lines[] = '- '.$step;
        }

        $lines[] = '';
        $lines[] = '## Evidence';
        $lines[] = '';
        foreach ((array) Arr::get($proposal, 'resources', []) as $resource) {
            $url = (string) Arr::get($resource, 'url', '');
            $type = (string) Arr::get($resource, 'type', 'other');
            $size = Arr::get($resource, 'transfer_size_kb');
            $lines[] = '- ['.$type.'] '.$url.' ('.$size.' KB)';
        }

        $lines[] = '';
        $lines[] = '_Generated at '.now()->toIso8601String().'_';

        return implode("\n", $lines)."\n";
    }

    private function confidenceForIssue(string $key): string
    {
        return match ($key) {
            'uses-optimized-images', 'uses-responsive-images', 'offscreen-images', 'modern-image-formats' => 'high',
            'render-blocking-resources', 'uses-text-compression', 'uses-long-cache-ttl', 'font-display' => 'medium',
            default => 'low',
        };
    }

    private function suggestTargetPaths(string $key): array
    {
        return match ($key) {
            'uses-optimized-images', 'uses-responsive-images', 'offscreen-images', 'modern-image-formats' => [
                'resources/**',
                'public/**',
            ],
            'render-blocking-resources', 'unused-javascript', 'unminified-javascript' => [
                'resources/**',
                'assets/**',
                'vite.config.*',
                'package.json',
            ],
            'unused-css-rules', 'unminified-css', 'font-display' => [
                'resources/**',
                'assets/**',
                'vite.config.*',
            ],
            default => [
                'resources/**',
            ],
        };
    }
}
